import type { Movie } from "../api/cinemaApi";

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    title: "Crimson Midnight",
    posterUrl: "https://picsum.photos/seed/crimson/500/750",
    description: "A detective hunts a copycat in a city where every shadow has a story.",
    rating: "R",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "CURRENTLY_RUNNING",
  },
  {
    id: 2,
    title: "Neon Alley",
    posterUrl: "https://picsum.photos/seed/neon/500/750",
    description: "Two strangers race a deadline through the underbelly of a glowing metropolis.",
    rating: "PG-13",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "CURRENTLY_RUNNING",
  },
  {
    id: 3,
    title: "Black Reel",
    posterUrl: "https://picsum.photos/seed/reel/500/750",
    description: "An indie filmmaker finds footage that was never meant to be seen.",
    rating: "PG-13",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "CURRENTLY_RUNNING",
  },
  {
    id: 4,
    title: "Coming Soon: Red Horizon",
    posterUrl: "https://picsum.photos/seed/horizon/500/750",
    description: "A stranded crew discovers a signal that changes what they believe about home.",
    rating: "PG",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "CURRENTLY_RUNNING",
  },
  {
    id: 5,
    title: "Coming Soon: The Last Ticket",
    posterUrl: "https://picsum.photos/seed/ticket/500/750",
    description: "A small-town theater gets one final screening… and it isn’t on any schedule.",
    rating: "PG-13",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "CURRENTLY_RUNNING",
  },
  {
    id: 6,
    title: "Coming Soon: White Noise",
    posterUrl: "https://picsum.photos/seed/noise/500/750",
    description: "A radio host starts receiving messages that predict tomorrow.",
    rating: "R",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "COMING_SOON",
  },
{
    id: 7,
    title: "Coming Soon: Red Horizon",
    posterUrl: "https://picsum.photos/seed/horizon/500/750",
    description: "A stranded crew discovers a signal that changes what they believe about home.",
    rating: "PG",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "COMING_SOON",
  },
  {
    id: 8,
    title: "Coming Soon: The Last Ticket",
    posterUrl: "https://picsum.photos/seed/ticket/500/750",
    description: "A small-town theater gets one final screening… and it isn’t on any schedule.",
    rating: "PG-13",
    genre: "Action",
    trailerUrl: "'https://youtu.be/UaVTIH8mujA?si=VMQRt3lJ-FlbA-Mn',",
    status: "COMING_SOON",
  },
];